// Components/spotsData.js

export const CATEGORIES = [
    { key: 'hist', label: 'Historical Landmarks', emoji: '🏛️' },
    { key: 'art',  label: 'Art & Design Spots',   emoji: '🎨' },
    { key: 'ent',  label: 'Entertainment',        emoji: '🎉' },
  ];
  
  export const SPOTS = [
    // 🏛️ Historical Landmarks
    {
      id: 'brandenburg-gate',
      title: 'Brandenburg Gate',
      categoryKey: 'hist',
      categoryLabel: 'Historical Landmarks',
      rating: 4.8,
      lat: 52.5163,
      lng: 13.3777,
      description: `The Brandenburg Gate is one of Berlin's most iconic neoclassical monuments, standing as a symbol of unity and peace. Built in the 18th century as a grand entrance to Unter den Linden boulevard, it witnessed many of Germany’s historical turning points—from Napoleon’s invasion to the Cold War division. When the Berlin Wall fell in 1989, it became a powerful symbol of German reunification. Today, tourists and locals gather around the Gate to reflect on the past and celebrate freedom, often accompanied by street musicians and vibrant cultural events.`,
      image: require('../assets/brandenburg.webp'),
    },
    {
      id: 'berliner-dom',
      title: 'Berlin Cathedral (Berliner Dom)',
      categoryKey: 'hist',
      categoryLabel: 'Historical Landmarks',
      rating: 4.7,
      lat: 52.5194,
      lng: 13.4010,
      description: `A majestic display of baroque architecture, the Berlin Cathedral is the largest church in the city. It houses the Hohenzollern crypt and a stunning dome that offers panoramic views of Berlin. Inside, ornate mosaics, statues, and an enormous Sauer organ create a sense of awe and reverence. Visitors often find themselves lingering in the tranquil atmosphere, contemplating the craftsmanship and the spiritual history held within its stone walls.`,
      image: require('../assets/berliner_dom.webp'),
    },
    {
      id: 'charlottenburg-palace',
      title: 'Charlottenburg Palace (Schloss Charlottenburg)',
      categoryKey: 'hist',
      categoryLabel: 'Historical Landmarks',
      rating: 4.6,
      lat: 52.5206,
      lng: 13.2956,
      description: `This baroque palace was originally built for Queen Sophie Charlotte in the 17th century and remains a testament to royal Prussian splendor. The palace's interiors are lavishly decorated with gilded ceilings, frescoes, and porcelain collections. The sprawling gardens, inspired by Versailles, offer peaceful walks along tree-lined paths, lakes, and classical statues. It's a perfect destination for history lovers and romantics alike.`,
      image: require('../assets/charlottenburg.webp'),
    },
    {
      id: 'reichstag',
      title: 'Reichstag Building',
      categoryKey: 'hist',
      categoryLabel: 'Historical Landmarks',
      rating: 4.7,
      lat: 52.5186,
      lng: 13.3762,
      description: `The Reichstag is the seat of the German parliament and a remarkable symbol of resilience and transformation. Originally opened in 1894, it was heavily damaged during WWII and later restored with a modern glass dome by architect Norman Foster. Visitors can walk inside this transparent dome, watching debates below and enjoying panoramic views of Berlin—representing both political transparency and national rebirth.`,
      image: require('../assets/reichstag.webp'),
    },
    {
      id: 'gendarmenmarkt',
      title: 'Gendarmenmarkt',
      categoryKey: 'hist',
      categoryLabel: 'Historical Landmarks',
      rating: 4.6,
      lat: 52.5138,
      lng: 13.3924,
      description: `Gendarmenmarkt is often called the most beautiful square in Berlin, framed by the German Cathedral, French Cathedral, and the majestic Konzerthaus. The elegant baroque architecture and cobbled square offer a serene atmosphere during the day and magical lighting by night. It's a place where history whispers through the marble and music floats through the air.`,
      image: require('../assets/gendarmenmarkt.webp'),
    },
  
    // 🎨 Art & Design Spots
    {
      id: 'east-side-gallery',
      title: 'East Side Gallery',
      categoryKey: 'art',
      categoryLabel: 'Art & Design Spots',
      rating: 4.8,
      lat: 52.5050,
      lng: 13.4394,
      description: `Stretching 1.3 kilometers along the remnants of the Berlin Wall, the East Side Gallery is the world’s longest open-air gallery. Over 100 artists from around the globe transformed the concrete symbol of division into a canvas of peace and hope. Iconic murals like “The Fraternal Kiss” continue to inspire dialogue about freedom, expression, and the power of art to reshape history.`,
      image: require('../assets/east_side_gallery.webp'),
    },
    {
      id: 'hamburger-bahnhof',
      title: 'Hamburger Bahnhof – Museum for Contemporary Art',
      categoryKey: 'art',
      categoryLabel: 'Art & Design Spots',
      rating: 4.5,
      lat: 52.5286,
      lng: 13.3672,
      description: `Once a railway station, Hamburger Bahnhof now houses an impressive collection of contemporary art. It features works by Joseph Beuys, Andy Warhol, and current avant-garde creators. With vast halls and experimental installations, the museum offers a bold journey through post-1960s artistic innovation. It’s not just a visit—it’s an immersion into Berlin’s role as a leading hub for creative minds.`,
      image: require('../assets/hamburger_bahnhof.webp'),
    },
    {
      id: 'urban-nation',
      title: 'Urban Nation Museum for Urban Contemporary Art',
      categoryKey: 'art',
      categoryLabel: 'Art & Design Spots',
      rating: 4.6,
      lat: 52.4952,
      lng: 13.3533,
      description: `Urban Nation is Berlin’s heartbeat of street art and graffiti culture. This ever-evolving museum showcases works by global street artists and curates exhibitions that reflect social issues and urban identity. Beyond the museum walls, the surrounding streets are an extension of the gallery, with massive murals, stencils, and creative rebellion echoing from every corner.`,
      image: require('../assets/urban_nation.webp'),
    },
    {
      id: 'kw-institute',
      title: 'KW Institute for Contemporary Art',
      categoryKey: 'art',
      categoryLabel: 'Art & Design Spots',
      rating: 4.5,
      lat: 52.5260,
      lng: 13.3895,
      description: `Tucked away in Mitte, KW Institute fosters cutting-edge contemporary art. It's a hotspot for progressive exhibitions, artist talks, and experimental media. The minimalist design of the building contrasts with the boldness of its content, where visitors encounter thought-provoking themes on politics, identity, and urban life.`,
      image: require('../assets/kw.webp'),
    },
    {
      id: 'berlinische-galerie',
      title: 'Berlinische Galerie',
      categoryKey: 'art',
      categoryLabel: 'Art & Design Spots',
      rating: 4.6,
      lat: 52.5025,
      lng: 13.4092,
      description: `This gallery focuses on Berlin-based artists from 1870 to the present, blending classical and contemporary styles. From expressionist paintings and Weimar-era photography to modern installations, it reflects the city’s turbulent artistic evolution. The sleek and airy layout provides space for immersive engagement with the artwork.`,
      image: require('../assets/berlinische_galerie.webp'),
    },
    {
      id: 'teufelsberg',
      title: 'Teufelsberg Graffiti and Street Art',
      categoryKey: 'art',
      categoryLabel: 'Art & Design Spots',
      rating: 4.4,
      lat: 52.5072,
      lng: 13.2413,
      description: `Teufelsberg is an abandoned Cold War-era US listening station built atop a rubble hill. It’s now a surreal outdoor gallery covered in sprawling graffiti and murals by local and international artists. Reaching the top offers expansive views of the Grunewald forest and Berlin skyline—a perfect blend of decay, defiance, and creative rebellion.`,
      image: require('../assets/teufelsberg.webp'),
    },
  
    // 🎉 Entertainment
    {
      id: 'klunkerkranich',
      title: 'Klunkerkranich Rooftop Bar',
      categoryKey: 'ent',
      categoryLabel: 'Entertainment',
      rating: 4.7,
      lat: 52.4807,
      lng: 13.4310,
      description: `Perched atop a parking garage in Neukölln, Klunkerkranich is a bohemian rooftop bar with a panoramic view of Berlin’s skyline. The ambiance is relaxed and artistic, often featuring live music, DJ sets, and creative cocktails. Wooden benches, urban gardens, and sunset vibes make this a favorite gathering spot for locals and travelers alike.`,
      image: require('../assets/klunkerkranich.webp'),
    },
    {
      id: 'markthalle-neun',
      title: 'Markthalle Neun',
      categoryKey: 'ent',
      categoryLabel: 'Entertainment',
      rating: 4.6,
      lat: 52.5009,
      lng: 13.4253,
      description: `Located in Kreuzberg, Markthalle Neun is a paradise for food lovers. This historic market hall offers a rotating selection of artisan foods, local produce, and international delicacies. Its Street Food Thursday event is particularly popular, bringing together flavors from around the world in a festive, communal atmosphere. The market combines history, gastronomy, and culture under one roof.`,
      image: require('../assets/markthalle_neun.webp'),
    },
    {
      id: 'berghain',
      title: 'Berghain / Panorama Bar',
      categoryKey: 'ent',
      categoryLabel: 'Entertainment',
      rating: 4.4,
      lat: 52.5113,
      lng: 13.4436,
      description: `Known globally as the techno mecca, Berghain is not just a club—it’s a Berlin institution. Housed in a former power plant, its industrial aesthetic and meticulously curated sound systems create a raw, immersive nightlife experience. With notoriously selective door policies and marathon weekend parties, it represents Berlin’s underground spirit like no other place.`,
      image: require('../assets/berghain.webp'),
    },
    {
      id: 'prater-garten',
      title: 'Prater Garten',
      categoryKey: 'ent',
      categoryLabel: 'Entertainment',
      rating: 4.6,
      lat: 52.5386,
      lng: 13.4141,
      description: `Berlin’s oldest beer garden, dating back to 1837, Prater Garten is a charming, leafy venue serving cold local beers and hearty German meals under chestnut trees. Despite its age, it retains a vibrant atmosphere and is a favorite summer hangout for both Berliners and tourists. The garden hums with cheerful chatter and the scent of grilled sausages.`,
      image: require('../assets/prater_garten.webp'),
    },
    {
      id: 'sisyphos',
      title: 'Sisyphos Club',
      categoryKey: 'ent',
      categoryLabel: 'Entertainment',
      rating: 4.5,
      lat: 52.4941,
      lng: 13.5023,
      description: `Sisyphos isn’t just a club—it’s a playground for night owls and free spirits. Located on the site of a former dog biscuit factory, it offers a riverside beach, food stalls, art installations, and eclectic music zones. The weekend parties often last until Monday, with a friendly, non-pretentious crowd and a vibe that feels more like a music festival than a nightclub.`,
      image: require('../assets/sisyphos.webp'),
    },
    {
      id: 'monkey-bar',
      title: 'Monkey Bar (25hours Hotel Bikini)',
      categoryKey: 'ent',
      categoryLabel: 'Entertainment',
      rating: 4.7,
      lat: 52.5064,
      lng: 13.3396,
      description: `Overlooking the Berlin Zoo, this stylish rooftop bar offers a jungle-themed interior and one of the best sunset views in the city. Watch monkeys swing in the trees below while sipping handcrafted cocktails. The vibe is cosmopolitan, and the interior is filled with cozy nooks, hanging plants, and warm lighting—a visual and sensory delight.`,
      image: require('../assets/monkey_bar.webp'),
    },
  ];
  